nelmio_cors:
    
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173'] # Adresse de votre frontend
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600

    paths:
        '^/api/':  # Autoriser les requêtes pour les routes sous /api/
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Type']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600

